{% set name = "whos-there" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/whos_there-{{ version }}.tar.gz
  sha256: 07bfb7a57d1f94895662a2d2421caaa3e8ed1995fc4d11ab5005f2160d924b2a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8.1
    - poetry
  run:
    - python >=3.8.1
    - python-telegram-bot >=20.0
    - pytorch-lightning >=1.8.0
    - requests >=2.28.2
    - lightning-utilities ==0.3.*

test:
  imports:
    - whos_there
    - whos_there.senders
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/twsl/whos-there
  summary: The spiritual successor to knockknock for PyTorch Lightning, get notified when your training ends
  license: MIT
  license_file: LICENSE
  description: |
    The spiritual successor to [knockknock](https://github.com/huggingface/knockknock) 
    for [PyTorch Lightning](https://github.com/PyTorchLightning/pytorch-lightning), 
    to get a notification when your training is complete or when it crashes during the 
    process with a single callback.

    ## 🚀 Features

    - Supports E-Mail, Discord, Slack, Teams, Telegram

  doc_url: https://github.com/twsl/whos-there
  dev_url: https://github.com/twsl/whos-there

extra:
  recipe-maintainers:
    - sugatoray
